// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Uuid = require("../src/Uuid.js");

var uuidv1 = Uuid.V1[/* uuidv1 */0](/* () */0);

console.log(uuidv1);

var uuidv3_1 = Uuid.V3[/* uuidv3 */0]("hello.example.com", /* DNS */0);

console.log(uuidv3_1);

var uuidv3_2 = Uuid.V3[/* uuidv3 */0]("http://example.com/hello", /* URL */1);

console.log(uuidv3_2);

var namespace1 = "1b671a64-40d5-491e-99b0-da01ff1f3341";

var uuidv3_3 = Uuid.V3[/* uuidv3 */0]("Hello, world!", /* Custom */[namespace1]);

console.log(uuidv3_3);

var uuidv4 = Uuid.V4[/* uuidv4 */0](/* () */0);

console.log(uuidv4);

var uuidv5_1 = Uuid.V5[/* uuidv5 */0]("hello.example.com", /* DNS */0);

console.log(uuidv5_1);

var uuidv5_2 = Uuid.V5[/* uuidv5 */0]("http://example.com/hello", /* URL */1);

console.log(uuidv5_2);

var namespace2 = "1b671a64-40d5-491e-99b0-da01ff1f3341";

var uuidv5_3 = Uuid.V5[/* uuidv5 */0]("Hello, world!", /* Custom */[namespace2]);

console.log(uuidv5_3);

exports.uuidv1 = uuidv1;
exports.uuidv3_1 = uuidv3_1;
exports.uuidv3_2 = uuidv3_2;
exports.namespace1 = namespace1;
exports.uuidv3_3 = uuidv3_3;
exports.uuidv4 = uuidv4;
exports.uuidv5_1 = uuidv5_1;
exports.uuidv5_2 = uuidv5_2;
exports.namespace2 = namespace2;
exports.uuidv5_3 = uuidv5_3;
/* uuidv1 Not a pure module */
