// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var V1 = require("uuid/v1");
var V3 = require("uuid/v3");
var V4 = require("uuid/v4");
var V5 = require("uuid/v5");

function uuidv1() {
  return V1();
}

var V1$1 = /* module */[/* uuidv1 */uuidv1];

function uuidv3(value, namespace) {
  if (typeof namespace === "number") {
    if (namespace !== 0) {
      return V3(value, V3.URL);
    } else {
      return V3(value, V3.DNS);
    }
  } else {
    return V3(value, namespace[0]);
  }
}

var V3$1 = /* module */[/* uuidv3 */uuidv3];

function uuidv4() {
  return V4();
}

var V4$1 = /* module */[/* uuidv4 */uuidv4];

function uuidv5(value, namespace) {
  if (typeof namespace === "number") {
    if (namespace !== 0) {
      return V5(value, V5.URL);
    } else {
      return V5(value, V5.DNS);
    }
  } else {
    return V5(value, namespace[0]);
  }
}

var V5$1 = /* module */[/* uuidv5 */uuidv5];

exports.V1 = V1$1;
exports.V3 = V3$1;
exports.V4 = V4$1;
exports.V5 = V5$1;
/* uuid/v1 Not a pure module */
